const String description = ""
    "Wawancara ini adalah siri penyelidikan tokoh seni negara iaitu Ibrahim Hussein bagi "
    "Pusat Penyelidikan Seni Asia Tenggara (PUSAT) sempena pameran ‘ARKIB: Archiving Ibrahim Hussein "
    "(Kenangan Bersama Muzium dan Yayasan Seni Ibrahim Hussein)’ yang diadakan pada 31 Mac "
    "hingga 31 Mei 2021 di Balai Seni Negara Langkawi. Pasukan kuratorial yang terdiri daripada "
    "Zanita Anuar, Faizal Sidik, Zulkarnain Zainal Abidin dan Hafiz Osman telah mengadakan satu "
    "lawatan penyelidikan rasmi semasa PKPB atau Perintah Kawalan Pergerakan Bersyarat ke Pulau "
    "Pinang pada 17 hingga 20 Mac 2021 ke rumah tokoh arkitek negara iaitu Datuk Seri Lim Chong Keat "
    "yang terletak di Jalan Macalister, George Town, Pulau Pinang bagi mewawancara beliau sebagai "
    "arkitek yang telah merancang dan membina Muzium dan Yayasan Ibrahim Hussein (IHMCF) di Pulau "
    "Langkawi pada tahun 1990 an. "
    "\n\n"
    "       Sepintas lalu latar belakang Datuk Seri Lim Chong Kiat, beliau "
    "dilahirkan di Pulau Pinang pada tahun 1930 yang merupakan rakan rapat Ibrahim Hussein. Mendapat "
    "didikan formal daripada Manchester University dan seni bina akuistik daripada Massachusetts "
    "Institute of Technology (MIT), beliau merupakan bekas Ketua dan Pengarah Jurubena Bertiga "
    "International Sdn Bhd iaitu firma seni bina yang menjalankan projek seni bina dan perundingan. "
    "Beliau merupakan arkitek yang membina rumah studio Ibrahim Hussein, Sim Hussein dan Alia yang "
    "terletak di Kuala Lumpur. Firma beliau banyak bertanggungjawab dalam projek perancangan dan "
    "pembinaan utama di Malaysia, Singapura dan luar negara. Selain itu beliau juga mempunyai minat "
    "yang mendalam dalam pemuliharaan taman botani. Selepas bersara daripada firma pada tahun "
    "1995 beliau dilantik sebagai Profesor Tamu di University of Manchester, England dan juga Felo "
    "Tamu di Emmanuel College, UK. Beliau menerima jemputan istimewa daripada Ibrahim Hussein untuk "
    "membina muzium seni yang terletak di taman rimba. Pada tahun 2002 beliau dianugerahkan gelaran "
    "Datuk Seni di atas sumbangannya terhadap pembangunan seni bina serantau. Antara seni bina yang "
    "dihasilkan oleh beliau dan Jurubena Bertiga adalah Menara Komtar, Bangunan Sultan Abdul Aziz Shah "
    "SSAAS (SUK Selangor), Dewan Sivik Petaling Jaya, Masjid Negeri Sembilan, (Malaysia) Jurong Town "
    "Hall, Singapore Conference Hall (Singapura).";

const String descriptionArt =
    "Art lovers can view thousands of paintings, sculptures, installations "
    "and new work online – many in minute detail – as well as explore the "
    "museums themselves. There are various platforms: from interactive, "
    "360-degree videos and full “walk-around” tours with voiceover "
    "descriptions to slideshows with zoomable photos of the world’s "
    "greatest artworks. And many allow viewers to get closer to the art than "
    "they could do in real life. "
    "\n\n"
    "So, take a break from the news, enter full-screen mode and start your "
    "art.";

const String description360 =
    "Our virtual tour gallery is a window into our hearts as people, "
    "artists, and professionals. This is where we post some of the virtual tour projects that we "
    "have produced for our clients. Across industries—from exhibitions, tradeshows, properties and "
    "museums to factories and businesses—we have done countless 360 virtual tour projects. "
    "\n\n"
    "Inside "
    "our virtual tour gallery, you are welcome to view any of our fantastic 360 degree virtual tour"
    " projects in great detail.. ";
